name: Hugo website (beta)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pages: write

on:
  workflow_call:
    inputs:
      cache-version:
        required: false
        type: string
        default: v1
      hugo-version:
        required: true
        type: string
      build-path:
        required: false
        type: string
        default: build
      timezone:
        required: false
        type: string
        default: Europe/London

env:
  NODE_ENV: test

jobs:

  verify:
    name: Verify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run --if-present verify

  test:
    name: Run tests
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: ${{ inputs.timezone }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo-version }}
          extended: true
      - run: npm ci
      - run: npm run --if-present test

  build:
    name: Build the website
    needs: test
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo-cache
    steps:
      - uses: actions/checkout@v5
        with:
          # We need all history for .GitInfo and .Lastmod
          fetch-depth: 0
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: ${{ inputs.timezone }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo-version }}
          extended: true
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.HUGO_CACHEDIR }}
            ${{ inputs.build-path }}
            resources/_gen
          key: ${{ runner.os }}-build-${{ inputs.cache-version }}-${{ hashFiles('config', 'content', 'data', 'themes') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ inputs.cache-version }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run --if-present build
      - uses: actions/upload-pages-artifact@v3
        if: github.ref_name == github.event.repository.default_branch
        with:
          path: ${{ inputs.build-path }}

  deploy:
    name: Deploy the website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
