name: Node.js package (single)

on:
  workflow_call:
    inputs:
      nodeVersions:
        description: A JSON array of major version numbers to build with
        type: string
        default: '[24, 22, 20]'
    secrets:
      githubToken:
        required: true
      npmToken:
        required: true

env:
  NODE_ENV: test

jobs:
  verify:
    name: Verify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ fromJSON(inputs.nodeVersions)[0] }}
          cache: npm
      - run: npm ci
      - run: npm run --if-present verify

  test:
    name: Run tests in Node.js ${{ matrix.node }}
    needs: verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ fromJSON(inputs.nodeVersions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run --if-present test

  manage-releases:
    name: Manage PRs and GitHub Releases
    needs: test
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ fromJSON(inputs.nodeVersions)[0] }}
      - name: Create release PR
        run: |
          npx release-please@16 release-pr \
            --bump-minor-pre-major \
            --bump-patch-for-minor-pre-major \
            --release-type=node \
            --repo-url=${{ github.repository }} \
            --token=${{ secrets.githubToken }}
      - name: Create GitHub releases
        run: |
          npx release-please@16 github-release \
            --release-type=node \
            --repo-url=${{ github.repository }} \
            --token=${{ secrets.githubToken }}

  publish:
    name: Publish package
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ fromJSON(inputs.nodeVersions)[0] }}
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run --if-present build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npmToken }}
